# Generated by Django 4.2 on 2023-04-13 09:05

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('telecom', '0001_initial'), ('telecom', '0002_branch_line_smartphone_vivobox_delete_usersession'), ('telecom', '0003_line_action_alter_line_plan'), ('telecom', '0004_alter_line_action'), ('telecom', '0005_alter_line_action_alter_line_plan'), ('telecom', '0006_line_consumption_line_vip_alter_line_status'), ('telecom', '0007_line_accountable_line_status_rfp'), ('telecom', '0008_uploadfile_alter_line_accountable_and_more'), ('telecom', '0009_alter_uploadfile_file')]

    dependencies = [
        ('sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=255)),
                ('branch', models.IntegerField(default=0)),
                ('regional', models.CharField(default='-', max_length=3)),
                ('structure', models.CharField(default='-', max_length=31)),
                ('closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=255, verbose_name='Nome')),
                ('branch', models.IntegerField(default=0, verbose_name='Filial')),
                ('number', models.BigIntegerField(default=0, verbose_name='Número')),
                ('imei_1', models.CharField(default='-', max_length=15, verbose_name='IMEI 1')),
                ('imei_2', models.CharField(default='-', max_length=15, verbose_name='IMEI 2')),
                ('s_model', models.CharField(choices=[('LG K130F', 'LG K130F'), ('MOTO E4', 'Moto E4'), ('MOTO G4 Play', 'Moto G4 Play'), ('MOTO G5S', 'Moto G5S'), ('MOTO G8 Power Lite', 'Moto G8 Power Lite'), ('MOTO G20', 'Moto G20'), ('MOTO G22', 'Moto G22')], default='-', max_length=31, verbose_name='Modelo')),
                ('receipt', models.IntegerField(default=0, verbose_name='Nota Fiscal')),
                ('status', models.CharField(choices=[('ESTOQUE', 'Estoque'), ('CONFIGURADO', 'Configurado'), ('AGUARDANDO SCI', 'Aguard. SCI'), ('AGUARDANDO TERMO', 'Aguard. Termo'), ('TERMO ASSINADO', 'Termo Assinado'), ('AGUARDANDO ENDERECO', 'Aguard. End.'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('ROUBO', 'Roubo'), ('FURTO', 'Furto'), ('BLOQUEADO', 'Bloqueado'), ('QUEBRADO', 'Quebrado')], default='-', max_length=31, verbose_name='Status')),
                ('date_update', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('branch_closed', models.BooleanField(default=False)),
                ('auth_attachment', models.FileField(blank=True, upload_to='smartphone_docs/%Y/%m', verbose_name='Autorização')),
            ],
        ),
        migrations.CreateModel(
            name='VivoBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=255, verbose_name='Nome')),
                ('branch', models.IntegerField(default=0, verbose_name='Filial')),
                ('number', models.BigIntegerField(default=0, verbose_name='Número')),
                ('imei_1', models.CharField(default='-', max_length=15, verbose_name='IMEI 1')),
                ('v_model', models.CharField(choices=[('HUAWEI-E173', 'Huawei-E173'), ('MF253M', 'MF253M'), ('WLD71-T5', 'WLD71-T5'), ('BC-4GMCPGa', 'BC-4GMCPGa')], default='-', max_length=31, verbose_name='Modelo')),
                ('receipt', models.IntegerField(default=0, verbose_name='Nota Fiscal')),
                ('status', models.CharField(choices=[('ESTOQUE', 'Estoque'), ('CONFIGURADO', 'Configurado'), ('AGUARDANDO ENDERECO', 'Aguard. End.'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('ROUBO', 'Roubo'), ('FURTO', 'Furto'), ('BLOQUEADO', 'Bloqueado'), ('QUEBRADO', 'Quebrado')], default='-', max_length=31, verbose_name='Status')),
                ('date_update', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('branch_closed', models.BooleanField(default=False)),
                ('auth_attachment', models.FileField(blank=True, upload_to='vivobox_docs/%Y/%m', verbose_name='Autorização')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=255, verbose_name='Nome')),
                ('branch', models.IntegerField(default=0, verbose_name='Filial')),
                ('number', models.BigIntegerField(default=0, verbose_name='Número')),
                ('sim_card', models.CharField(default='-', max_length=20, verbose_name='SIM Card')),
                ('sim_card_old', models.CharField(default='-', max_length=20)),
                ('receipt', models.IntegerField(default=0, verbose_name='Nota Fiscal')),
                ('plan', models.CharField(choices=[('CLARO MAX 2.0', 'Claro Max 2.0'), ('CLARO ILIMITADO 2GB', 'Claro Ilimitado 2GB'), ('CLARO ILIMITADO 20GB', 'Claro Ilimitado 20GB'), ('TIM DADOS 3GB', 'TIM Dados 3GB'), ('TIM DADOS 6GB', 'TIM Dados 6GB'), ('VIVO MOVEL 120MB', 'Vivo Móvel 120MB'), ('VIVO BOX 5GB', 'Vivo Box 5GB'), ('VIVO BOX 10GB', 'Vivo Box 10GB'), ('VIVO SMART 0,5GB', 'Vivo Smart 0,5GB'), ('VIVO SMART 2GB', 'Vivo Smart 2GB'), ('VIVO SMART 5GB', 'Vivo Smart 5GB'), ('VIVO SMART 7GB', 'Vivo Smart 7GB'), ('VIVO SMART 25GB', 'Vivo Smart 25GB')], default='-', max_length=31, verbose_name='Plano')),
                ('telecom', models.CharField(choices=[('CLARO', 'Claro'), ('TIM', 'TIM'), ('VIVO', 'Vivo')], default='-', max_length=15, verbose_name='Operadora')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('BLOQUEADO', 'Bloqueado'), ('CANCELADO', 'Cancelado'), ('DISPONIVEL', 'Disponível')], default='-', max_length=31, verbose_name='Status')),
                ('date_update', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('branch_closed', models.BooleanField(default=False)),
                ('name_mapped', models.BooleanField(default=True, verbose_name='Nome Mapeado')),
                ('branch_mapped', models.BooleanField(default=True, verbose_name='CR Mapeado')),
                ('auth_attachment', models.FileField(blank=True, upload_to='line_docs/%Y/%m', verbose_name='Autorização')),
                ('action', models.CharField(choices=[('OK', 'Ok'), ('CANCELAR APOS FIDELIDADE', 'Cancelar Após Fidelidade'), ('CANCELAR EM MAIO', 'Cancelar em Maio'), ('MAPEAR', 'Mapear')], default='OK', max_length=31, verbose_name='Ação')),
                ('consumption', models.CharField(choices=[('COM CONSUMO', 'Com Consumo'), ('SEM CONSUMO 1 MES', 'Sem Consumo 1 Mês'), ('SEM CONSUMO 2 MESES', 'Sem Consumo 2 Meses'), ('SEM CONSUMO 3 MESES', 'Sem Consumo 3 Meses'), ('SEM CONSUMO 4 MESES', 'Sem Consumo 4 Meses')], default='COM CONSUMO', max_length=63, verbose_name='Consumo')),
                ('vip', models.BooleanField(default=False, verbose_name='VIP')),
                ('accountable', models.CharField(choices=[('MAPEADO', 'Mapeado'), ('TG', 'TG'), ('SAPORE', 'Sapore')], default='ATIVO', max_length=63, verbose_name='Responsável')),
                ('status_rfp', models.CharField(choices=[('ATIVO', 'Ativo'), ('ATIVO FORA RFP', 'Ativo Fora RFP'), ('BLOQUEADO', 'Bloqueado'), ('BLOQUEADO FORA RFP', 'Bloqueado Fora RFP'), ('SUSPENSO', 'Suspenso'), ('SUSPENSO FORA RFP', 'Suspenso Fora RFP'), ('CANCELADO', 'Cancelado')], default='-', max_length=31, verbose_name='Status RFP')),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Planilha')),
            ],
        ),
    ]
