# Generated by Django 4.2 on 2023-04-06 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=255)),
                ('branch', models.IntegerField(default=0)),
                ('regional', models.CharField(default='-', max_length=3)),
                ('structure', models.CharField(default='-', max_length=31)),
                ('closed', models.CharField(default='-', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=255, verbose_name='Nome')),
                ('branch', models.IntegerField(default=0, verbose_name='Filial')),
                ('number', models.BigIntegerField(default=0, verbose_name='Número')),
                ('sim_card', models.CharField(default='-', max_length=20, verbose_name='SIM Card')),
                ('sim_card_old', models.CharField(default='-', max_length=20)),
                ('receipt', models.IntegerField(default=0, verbose_name='Nota Fiscal')),
                ('plan', models.CharField(choices=[('BOX', 'Box'), ('MODEM', 'Modem'), ('SMART', 'Smart')], default='-', max_length=31, verbose_name='Plano')),
                ('telecom', models.CharField(choices=[('CLARO', 'Claro'), ('TIM', 'TIM'), ('VIVO', 'Vivo')], default='-', max_length=15, verbose_name='Operadora')),
                ('status', models.CharField(choices=[('VERIFICANDO', 'Verificando'), ('SEM CONSUMO', 'Sem Consumo'), ('AGUARDANDO ATIVACAO', 'Aguard. Ativ.'), ('AGUARDANDO ENDERECO', 'Aguard. Endereço'), ('ATIVO', 'Ativo'), ('DISPONIVEL', 'Disponível'), ('ATUALIZADO', 'Atualizado'), ('NAO ATUALIZADO', 'Não Atualizado'), ('BLOQUEADO', 'Bloqueado'), ('CANCELADO', 'Cancelado'), ('VIP', 'VIP'), ('CR ENCERRADO', 'CR Encerrado')], default='-', max_length=31, verbose_name='Status')),
                ('date_update', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=255, verbose_name='Nome')),
                ('branch', models.IntegerField(default=0, verbose_name='Filial')),
                ('number', models.BigIntegerField(default=0, verbose_name='Número')),
                ('imei_1', models.CharField(default='-', max_length=15, verbose_name='IMEI 1')),
                ('imei_2', models.CharField(default='-', max_length=15, verbose_name='IMEI 2')),
                ('s_model', models.CharField(choices=[('LG K130F', 'LG K130F'), ('MOTO E4', 'Moto E4'), ('MOTO G4 Play', 'Moto G4 Play'), ('MOTO G5S', 'Moto G5S'), ('MOTO G8 Power Lite', 'Moto G8 Power Lite'), ('MOTO G20', 'Moto G20'), ('MOTO G22', 'Moto G22')], default='-', max_length=31, verbose_name='Modelo')),
                ('receipt', models.IntegerField(default=0, verbose_name='Nota Fiscal')),
                ('status', models.CharField(choices=[('ESTOQUE', 'Estoque'), ('CONFIGURADO', 'Configurado'), ('AGUARDANDO SCI', 'Aguard. SCI'), ('AGUARDANDO TERMO', 'Aguard. Termo'), ('TERMO ASSINADO', 'Termo Assinado'), ('AGUARDANDO ENDERECO', 'Aguard. End.'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('RETORNOU', 'Retornou'), ('ROUBO', 'Roubo'), ('FURTO', 'Furto'), ('BLOQUEADO', 'Bloqueado'), ('QUEBRADO', 'Quebrado'), ('CR ENCERRADO', 'CR Encerrado')], default='-', max_length=31, verbose_name='Status')),
                ('date_update', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VivoBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=255, verbose_name='Nome')),
                ('branch', models.IntegerField(default=0, verbose_name='Filial')),
                ('number', models.BigIntegerField(default=0, verbose_name='Número')),
                ('imei_1', models.CharField(default='-', max_length=15, verbose_name='IMEI 1')),
                ('v_model', models.CharField(choices=[('HUAWEI-E173', 'Huawei-E173'), ('MF253M', 'MF253M'), ('WLD71-T5', 'WLD71-T5'), ('BC-4GMCPGa', 'BC-4GMCPGa')], default='-', max_length=31, verbose_name='Modelo')),
                ('receipt', models.IntegerField(default=0, verbose_name='Nota Fiscal')),
                ('status', models.CharField(choices=[('ESTOQUE', 'Estoque'), ('CONFIGURADO', 'Configurado'), ('AGUARDANDO ENDERECO', 'Aguard. End.'), ('ENVIADO', 'Enviado'), ('ENTREGUE', 'Entregue'), ('RETORNOU', 'Retornou'), ('ROUBO', 'Roubo'), ('FURTO', 'Furto'), ('BLOQUEADO', 'Bloqueado'), ('QUEBRADO', 'Quebrado'), ('CR ENCERRADO', 'CR Encerrado')], default='-', max_length=31, verbose_name='Status')),
                ('date_update', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
