# Generated by Django 4.2 on 2023-05-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoxModel',
            new_name='VivoboxModel',
        ),
    ]
