# Generated by Django 4.2 on 2023-05-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0002_rename_boxmodel_vivoboxmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmartModel',
            new_name='SmartphoneModel',
        ),
        migrations.RenameModel(
            old_name='SmartStatus',
            new_name='SmartphoneStatus',
        ),
        migrations.RenameModel(
            old_name='BoxStatus',
            new_name='VivoboxStatus',
        ),
    ]
