# Generated by Django 4.2 on 2023-05-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0003_rename_smartmodel_smartphonemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='tracking_code',
            field=models.CharField(default='-', max_length=13, verbose_name='Código de Rastreio'),
        ),
        migrations.AddField(
            model_name='vivobox',
            name='tracking_code',
            field=models.CharField(default='-', max_length=13, verbose_name='Código de Rastreio'),
        ),
    ]
