# Generated by Django 4.2 on 2023-04-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0003_line_action_alter_line_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='action',
            field=models.CharField(choices=[('OK', 'Ok'), ('CANCELAR EM MAIO', 'Cancelar em Maio'), ('CANCELAR APOS FIDELIDADE', 'Cancelar Após Fidelidade'), ('MAPEAR', 'Mapear')], default='OK', max_length=31, verbose_name='Ação'),
        ),
    ]
