# Generated by Django 4.2 on 2023-04-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0005_alter_line_action_alter_line_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='consumption',
            field=models.CharField(choices=[('COM CONSUMO', 'Com Consumo'), ('SEM CONSUMO 1 MES', 'Sem Consumo 1 Mês'), ('SEM CONSUMO 2 MES', 'Sem Consumo 2 Mês'), ('SEM CONSUMO 3 MES', 'Sem Consumo 3 Mês'), ('SEM CONSUMO 4 MES', 'Sem Consumo 4 Mês')], default='COM CONSUMO', max_length=63, verbose_name='Consumo'),
        ),
        migrations.AddField(
            model_name='line',
            name='vip',
            field=models.BooleanField(default=False, verbose_name='VIP'),
        ),
        migrations.AlterField(
            model_name='line',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('BLOQUEADO', 'Bloqueado'), ('CANCELADO', 'Cancelado'), ('DISPONIVEL', 'Disponível')], default='-', max_length=31, verbose_name='Status'),
        ),
    ]
