# Generated by Django 4.2 on 2023-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0006_line_consumption_line_vip_alter_line_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='accountable',
            field=models.CharField(choices=[('SAPORE', 'Sapore'), ('TG', 'TG'), ('MAPEADO', 'Mapeado')], default='ATIVO', max_length=63, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='line',
            name='status_rfp',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ATIVO FORA RFP', 'Ativo Fora RFP'), ('BLOQUEADO', 'Bloqueado'), ('BLOQUEADO', 'Bloqueado'), ('SUSPENSO', 'Suspenso'), ('SUSPENSO FORA RFP', 'Suspenso Fora RFP'), ('CANCELADO', 'Cancelado')], default='-', max_length=31, verbose_name='Status'),
        ),
    ]
