# Generated by Django 4.2 on 2023-04-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0007_line_accountable_line_status_rfp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='line',
            name='accountable',
            field=models.CharField(choices=[('MAPEADO', 'Mapeado'), ('TG', 'TG'), ('SAPORE', 'Sapore')], default='ATIVO', max_length=63, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='line',
            name='consumption',
            field=models.CharField(choices=[('COM CONSUMO', 'Com Consumo'), ('SEM CONSUMO 1 MES', 'Sem Consumo 1 Mês'), ('SEM CONSUMO 2 MESES', 'Sem Consumo 2 Meses'), ('SEM CONSUMO 3 MESES', 'Sem Consumo 3 Meses'), ('SEM CONSUMO 4 MESES', 'Sem Consumo 4 Meses')], default='COM CONSUMO', max_length=63, verbose_name='Consumo'),
        ),
        migrations.AlterField(
            model_name='line',
            name='status_rfp',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ATIVO FORA RFP', 'Ativo Fora RFP'), ('BLOQUEADO', 'Bloqueado'), ('BLOQUEADO FORA RFP', 'Bloqueado Fora RFP'), ('SUSPENSO', 'Suspenso'), ('SUSPENSO FORA RFP', 'Suspenso Fora RFP'), ('CANCELADO', 'Cancelado')], default='-', max_length=31, verbose_name='Status RFP'),
        ),
    ]
