# Generated by Django 4.2 on 2023-04-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0010_boxmodel_smartmodel_telecomplanmodel_delete_branch_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelecomPlanModel',
            new_name='LinePlanModel',
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='s_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telecom.smartmodel', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='vivobox',
            name='v_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='telecom.boxmodel', verbose_name='Modelo'),
        ),
    ]
