# Generated by Django 4.2 on 2023-04-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0011_rename_telecomplanmodel_lineplanmodel_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinePlanModel',
            new_name='LinePlan',
        ),
    ]
