# Generated by Django 4.2 on 2023-04-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telecom', '0013_remove_boxmodel_date_release_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='number',
            field=models.BigIntegerField(default=0, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='lineplan',
            name='name',
            field=models.CharField(default='-', max_length=31, unique=True, verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='imei_1',
            field=models.CharField(default='-', max_length=15, unique=True, verbose_name='IMEI 1'),
        ),
        migrations.AlterField(
            model_name='vivobox',
            name='imei_1',
            field=models.CharField(default='-', max_length=15, unique=True, verbose_name='IMEI 1'),
        ),
    ]
