# Generated by Django 4.2 on 2023-05-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='-', max_length=255, verbose_name='Nome')),
                ('query', models.TextField(verbose_name='Query')),
                ('visible', models.BooleanField(default=True, verbose_name='Visível')),
            ],
        ),
    ]
