# Generated by Django 4.2 on 2023-04-13 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.IntegerField(default=0)),
                ('name', models.CharField(default='-', max_length=255)),
                ('structure', models.CharField(default='-', max_length=31)),
                ('closed', models.BooleanField(default=False)),
                ('regional', models.CharField(default='-', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='', verbose_name='Planilha')),
                ('date_update', models.DateField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
