# Generated by Django 4.2 on 2023-04-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='branch',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
